name: Server unit test

on:
  push:
    branches:
      - main
    paths:
      - 'er-server/*'
  pull_request:
    branches:
      - main
    paths:
      - 'er-server/*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update rust toolchain
      run: |
        rustup update
        rustup install nightly        

    - name: Toolchain info
      run: |
        cargo --version --verbose
        rustc --version
  
    - name: Build and test
      run: |
        cd er-server
        cargo check
        cargo test --all    
